#//////////////////////////////////////////////////////////////////////
#   This Code Has been generated by Abhiyanta Community, India
#   Email: abhiyanta.ind@gmail.com
#   Git Hub: https://github.com/Abhiyanta-Community
#////////////////////////////////////////////////////////////////////////
clc
clear all;

#Reading Exceldata of Gyroscope
ReadXcel = xlsread('csv_matter.xlsx', 'Sheet1','A2:L1001');
G_XOUT_H = ReadXcel(:,7);
G_XOUT_L = ReadXcel(:,8);
G_YOUT_H = ReadXcel(:,9);
G_YOUT_L = ReadXcel(:,10);
G_ZOUT_H = ReadXcel(:,11);
G_ZOUT_L = ReadXcel(:,12);

#Convert 2 8bit of gyroscope mapped data into 16bit mapped number
res4 = double(typecast([uint8(G_XOUT_L), uint8(G_XOUT_H)], 'int16'))
res5 = double(typecast([uint8(G_YOUT_L), uint8(G_YOUT_H)], 'int16'))
res6 = double(typecast([uint8(G_ZOUT_L), uint8(G_ZOUT_H)], 'int16'))

#Set cutoff frequency and acontrolling factor alpha
fc = 600;
RC = 1/(2*pi*fc) ;
alpha =  RC / (RC+0.01);
pkg load signal

#Part for unmapping data of gyroscope which is in scale range +/-250 
Part = 500/65535;

for i=1:((length(res4)))
  if res4(i)<0
    gyr1(i)=-250+(-res4(i)*0.0076);
  endif
  if res4(i)>0
    gyr1(i)=250-(res4(i)*0.0076);
  endif
endfor

t=0:0.01:9.99;
subplot(2,1,1);
plot(t,gyr1);

#applying high pass filter on unmapped data of gyroscope and plotting graph 
fil4(1)=gyr1(1)
for i=1:((length(gyr1))-1)  
  fil4(i+1)=alpha*fil4(i) + (alpha*(gyr1(i+1)-gyr1(i))) 
endfor

t=0:0.01:9.99;
subplot(2,1,2);
plot(t,fil4)
#{
for i=1:((length(res5)))
  if res5(i)<0
    gyr2(i)=-250+(-res5(i)*0.0076);
  endif
  if res5(i)>0
    gyr2(i)=250-(res5(i)*0.0076);
  endif
endfor

t=0:0.01:9.99;
subplot(3,1,2);
plot(t,gyr2);

fil5(1)=gyr2(1)
for i=1:((length(gyr2))-1)  
  fil5(i+1)=alpha*fil5(i) + (alpha*(gyr2(i+1)-gyr2(i))) 
endfor

t=0:0.01:9.99;
subplot(3,2,2);
plot(t,fil5)

for i=1:((length(res6)))
  if res6(i)<0
    gyr3(i)=-250+(-res6(i)*0.0076);
  endif
  if res6(i)>0
    gyr3(i)=250-(res6(i)*0.0076);
  endif
endfor

t=0:0.01:9.99;
subplot(3,1,3);
plot(t,gyr3);

fil6(1)=gyr3(1)
for i=1:((length(gyr3))-1)  
  fil6(i+1)=alpha*fil6(i) + (alpha*(gyr3(i+1)-gyr3(i))) 
endfor

t=0:0.01:9.99;
subplot(3,2,3);
plot(t,fil6)
#}
